#NUMPY

Numpy is a general purpose array-processing package.
It provides a high-performance multidimensional array object, and tools for working with these arrays.
It is the fundamental package for scientific computing with Python.

In [4]:
#pip install numpy

Difference between list and numpy in python

- List in python is a linear data structure and can hold heterogeneous elements.
- Numpy array can hold homogeneous elements.
- List are flexible to shrink and grow.
- Arrays require less memory than list.

- The similarity between an array and a list is that the elements of both array and a list can be identified by its index value.

Conversion of list to arraya and vice-versa

In [5]:
import numpy as np
l = [1,2,3,4]
print(type(l))
arr = np.array(l)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


shape - shape will basically return us the total number of rows and columns of the array in a tuple format.

size - tell us the total number of elements or values present in the array.

dtype - tell us the data type of values which the array is containing.

In [6]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b.shape)
print(b.size)
print(b.dtype)

(2, 4)
8
int64


Numpy zeros - The numpy.zeros() function returns a new array of given shape and type, with zeros.

SYNTAX : numpy.zeros(shape, dtype=None, order='C')

In [9]:
a = np.zeros([2,2], dtype = int)
print("Matrix b : \n", a)

Matrix b : 
 [[0 0]
 [0 0]]


Numpy ones - The numpy.ones() function returns a new array of given shape and type, with ones.

SYNTAX : numpy.ones(shape, dtype = None, order = 'C')

In [10]:
ones = np.ones([2,2,2], dtype = float)
print("Matrix ones : \n", ones)

Matrix ones : 
 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
