numpy random - numpy.random.random() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval[0.0.1.0).

SYNTAX : numpy.random.random(size=None)

In [2]:
import numpy as np
arr = np.random.random(3)
print("Output 1D array filled with random floats : ",arr)
arr1 = np.random.random([2,2])
print("Output 2D array filled with float numbers : ",arr1)

Output 1D array filled with random floats :  [0.90270565 0.12284693 0.4463925 ]
Output 2D array filled with float numbers :  [[0.20316395 0.64569715]
 [0.15964137 0.2020266 ]]


Numpy arange - The arange([start,] stop[,step,][,dtype]) returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened.

In [6]:
print("A\n", np.arange(4).reshape(2,2), "\n")
print("A\n", np.arange(3,8,2.7,int), "\n")

A
 [[0 1]
 [2 3]] 

A
 [3 5] 



Numpy linspace - The numpy.linspace() function returns number spaces evenly with respect to interval. In case of steps, it uses sample number.

SYNTAX : numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None)

Parameters :
restep: If True, return (samples,step). By default restep = False
num : number of samples to generate
dtype : type of output array

In [7]:
print(np.linspace(0,2,10))

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


Numpy reshape - The numpy.reshape() function shapes an array without changing the data of the array.

SYNTAX : numpy.reshape(array, shape, order='C')

In [8]:
print("A\n", np.arange(4), "\n")
print("A\n", np.arange(4).reshape(2,2), "\n")

A
 [0 1 2 3] 

A
 [[0 1]
 [2 3]] 

