-Numpy achieves its fast implementation using vectorization.
-In numpy arrays developer can perform the same mathematical operation on every element with a single command.

In [14]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np
a = np.array([2,8,6,9])
b = np.array([5,3,4,7])

# add_ans = a + b
# print(add_ans)

# add_ans = np.add(a,b)
# print(add_ans)

c= np.array([1,5,8,9])
add_ans1 = np.add(b,c)
print(add_ans1)

sub_ans = np.subtract(a,b)
print(sub_ans)

mul_ans = np.multiply(b,c)
print(mul_ans)

div_ans = np.divide(a,c)
print(div_ans)

[ 6  8 12 16]
[-3  5  2  2]
[ 5 15 32 63]
[2.   1.6  0.75 1.  ]


-> numpy.max() - returns the maximum element of the given array

-> numpy.min() - returns the minimum element of the given array

-> numpy.max(arr,0) - here 0 will give us a list containing the maximum values from each column.

-> numpy.max(arr,1) - here 1 will give us a list containing the maximum values from each row.

In [9]:
import numpy as np
arr = np.array([[1,2,6,5],
                   [5,8,9,7],
                   [8,2,6,9]])

max_element = np.max(arr)
min_element = np.min(arr)
print(max_element)
print(min_element)

max_element_column = np.max(arr,0)
min_element_column = np.min(arr,0)

max_element_row = np.max(arr,1)
min_element_row = np.min(arr,1)

print("maximum elements in the column are :",max_element_column)
print("maximum elements in the row are :",max_element_row)
print("minimum elements in the column are :",min_element_column)
print("minimum elements in the row are :",min_element_row)

9
1
maximum elements in the column are : [8 8 9 9]
maximum elements in the row are : [6 9 9]
minimum elements in the column are : [1 2 6 5]
minimum elements in the row are : [1 5 2]
