Sort a Numpy array using the sort()

In [4]:
import numpy as np
a = np.array([[15,12],[5,25]])

#sort along the first axis
arr1 = np.sort(a, axis = 0)
print("Along the first axis : \n", arr1)

#sort along the last axis
arr2 = np.sort(a, axis= -1)
print("Along the last axis :\n", arr2)

#sort along none axis
arr3= np.sort(a, axis=None)
print("Along the none : \n",arr3)

Along the first axis : 
 [[ 5 12]
 [15 25]]
Along the last axis :
 [[12 15]
 [ 5 25]]
Along the none : 
 [ 5 12 15 25]


We can also choose which type of sorting we want to perform using the kind parameter inside the sort function. We can either choose quicksort, mergesort and heapsort.

In [7]:
arr = np.array([[7,3,6,9,7,5],[6,9,5,8,2,6]])
print(np.sort(arr, axis = -1, kind = 'mergesort'))

[[3 5 6 7 7 9]
 [2 5 6 6 8 9]]


# Array Merging

-> numpy.vstack() - is used to stack the sequence of input arrays vertically to make a single array.

SYNTAX : numpy.vstack(tup)

-> numpy.hstack() - is used to stack the sequence fo input arrays horizontally(i.e. column wise) to make a single array.

SYNTAX : numpy.hstack(tup)

-> numpy.concatenate() - function concatenate a sequence of arrays along an existing axis.

SYNTAX : numpy.concatenate((arr1,arr2,...), axis=0, out=None)

In [15]:
import numpy as np

arr1 = np.array([[1,2,3,1],[5,6,4,7]])
arr2 = np.array([[5,4,3,8],[55,78,32,6]])
vstack_arr = np.vstack((arr1, arr2))
hstack_arr = np.hstack((arr1, arr2))
print("Vertically Stacked arrays : \n",vstack_arr)
print("Horizontally Stacked arrays : \n",hstack_arr)

gfg = np.concatenate((arr1,arr2),axis = 0)
print(gfg)


Vertically Stacked arrays : 
 [[ 1  2  3  1]
 [ 5  6  4  7]
 [ 5  4  3  8]
 [55 78 32  6]]
Horizontally Stacked arrays : 
 [[ 1  2  3  1  5  4  3  8]
 [ 5  6  4  7 55 78 32  6]]
[[ 1  2  3  1]
 [ 5  6  4  7]
 [ 5  4  3  8]
 [55 78 32  6]]


# Splitting Arrays

-> numpy.vsplit() - this function split an array into multiple sub-arrays vertically(row-wise). vsplit is equivalent to split with axis=0, the array is always split along the axis regardless of the array dimension.

SYNTAX : numpy.vsplit(arr, indices_or_sections)

-> numpy.hsplit() - function split an array into multiple sub-arrays horizontally (column-wise). hsplit is equivalent to split with axis=1, the array is always split along the second axis regardless of the array dimension.

SYNTAX : numpy.hsplit(arr, indices_or_sections)

In [17]:
arr1 = np.array([[1,2,3,1],[5,6,4,7]])
arr2 = np.array([[5,4,3,8],[55,78,32,6]])

gfg1 = np.hsplit(arr1, 2)
print(gfg1)

gfg2 = np.vsplit(arr1,2)
print(gfg2)

[array([[1, 2],
       [5, 6]]), array([[3, 1],
       [4, 7]])]
[array([[1, 2, 3, 1]]), array([[5, 6, 4, 7]])]
